first_project_v1/first_app/urls.py
from django.contrib import admin
from django.urls import path
from first_app import views
from django.urls import re_path

app_name = 'first_app'

urlpatterns = [
    re_path(r'^$',views.base,name="base"),
    re_path(r'^/other',views.other,name="other"),
    re_path(r'^/relative',views.relative,name="relative"),
    re_path(r'^/register',views.register,name="register")

    # path('/help',views.help),

]

first_project_v1/first_project_v1/urls.py
from django.contrib import admin
from django.urls import path
from first_app import views
from django.conf.urls import include


urlpatterns = [
    path('first_app',include('first_app.urls')),
    path('',views.index,name='index'),
    path('admin/', admin.site.urls),
    path('login',views.user_login,name='login'),
    path('logout',views.user_log_out,name='logout')
]

first_project_v1/first_app/models.py
from attr import NOTHING
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfileInfo(models.Model):

    user = models.OneToOneField(User,on_delete=models.DO_NOTHING)
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username
    

first_project_v1/first_app/forms.py
from django import forms 
from django.contrib.auth.models import User
from first_app.models import UserProfileInfo


class UserForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput() )
    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

first_project_v1/first_app/views.py
from django.shortcuts import render
from django.http import  HttpResponse
from first_app.forms import UserForm,UserProfileInfoForm
from first_app.models import UserProfileInfo


from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect,HttpResponse
from django.urls  import reverse
from django.contrib.auth.decorators import login_required



def index(request):
   my_dict = {"insert_me" : "Hey I'm Expermineting Relative urls in this project!"}
   return render(request,"first_app/index.html",context=my_dict)

def base(request):
   my_dict = {"find_me" : "I'm being edited from first_app/views.py!"}
   return render(request,"first_app/base.html",context=my_dict)

def other(request):
   my_dict = {"other_me" : "I'm being edited from first_app/views.py!" , "other_2" : "rcb rocks"}
   return render(request,"first_app/other.html",context=my_dict)

def relative(request):
   my_dict = {"relative_me" : "I'm being edited from first_app/views.py!"}
   return render(request,"first_app/relative_url.html",context=my_dict)

def register(request):
   # sourcery skip: extract-method, inline-immediately-returned-variable
   registered = False 
   
   if request.method == "POST" :
      user_form = UserForm(data=request.POST)
      profile_form = UserProfileInfoForm(data=request.POST)

      if user_form.is_valid() and profile_form.is_valid():
         user = user_form.save()
         user.set_password(user.password)
         user.save()
         profile = profile_form.save(commit = False)
         profile.user =user

         if 'profile_pic' in request.FILES:
            profile.profile_pic = request.FILES['profile_pic']

         profile.save()

         registered = True
      else:
         print(user_form.errors,profile_form.errors)
   else:
      user_form = UserForm()
      profile_form = UserProfileInfoForm()

   return render(request,'first_app/registration.html',{'user_form':user_form,'profile_form':profile_form,'registered':registered})



         
def user_login(request):
   # sourcery skip: last-if-guard, remove-unnecessary-else, swap-if-else-branches, use-fstring-for-formatting, use-named-expression

   if request.method == 'POST':
      username = request.POST.get('username')
      password = request.POST.get('password')
   
      user = authenticate(username=username,password=password)

      if user:
         if user.is_active:
            login(request,user)
            print("usr : {}".format(user.is_authenticated))
            return HttpResponseRedirect(reverse('index'))
         else:
            return HttpResponse("Acount Not Active ")
      else:
         print("Someone Tried to login and failes")
         print("3 username : {} and password : {}".format(username,password) )
         return HttpResponse("Acount Does Not Exist")
   else:
      return render(request, 'first_app/login.html')

@login_required
def user_log_out(request):
   logout(request)
   return HttpResponseRedirect(reverse('index'))

      

            





      

first_project_v1/templates/first_app/base.html
<!DOCTYPE html>
{% extends "first_app/index.html" %}
{% block body_block %}
    <h1>Hey This is My base PAGE </h1>
    {{ find_me }}
{% endblock %}

first_project_v1/templates/first_app/index.html
<!DOCTYPE html>
{% load static  %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Index Page</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light ">
        <div class="navbar-nav">
          <a class="navbar-brand" href="{% url 'index'%}">DJANGO</a>
          <a class="nav-item nav-link" href="{% url 'first_app:register' %}">Register</a>
          {% if user.is_authenticated %}
          <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
          <a class="nav-item nav-link" href="{% url 'admin:index' %}">Admin</a>
          <a class="nav-item nav-link" href="{% url 'first_app:base' %}">Base</a>
          <a class="nav-item nav-link" href="{% url 'first_app:other' %}">Other</a>
          <a class="nav-item nav-link" href="{% url 'first_app:relative' %}">Relative</a>
          {% else %}
          <a class="nav-item nav-link" href="{% url 'login' %}">LOGIN</a>
          {% endif %}
        </div> 
    </nav>
    <div class="container">
    <div class ="jumbotron">
        {% block body_block %}
        <div class ="jumbotron">
        <h1 class="display-4">WELCOME TO MY INDEX PAGE</h1>
        <img src="{%static "images\download1.jpeg" %}" alt="Uh oh ,it didn't show!"><br>
        <br>
        <p>{{ insert_me }}</p>
        </div>
        {% endblock %}
    </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

first_project_v1/templates/first_app/login.html
{% extends "first_app/index.html" %}
{% block body_block %}
<div class="container">
    <div class="jumbotron">
        <h1>Please Login</h1>
    
        <form action="{% url 'login' %}" method="post">
        {% csrf_token %}
        <label for="username">username</label>
        <input type="text" name="username" placeholder="Enter User name">
        <br>
        <br>
        <label for="password">Password</label>
        <input type="password" name="password" placeholder="Enter password">
        <br>
        <input type="submit" name="" value="Login"> 
        </form>
    </div>
</div>
{% endblock %}

first_project_v1/templates/first_app/other.html
<!DOCTYPE html>
{% extends "first_app/index.html" %}
{% block body_block %}
{% load my_extras %}
    <h1>Hey This is My Other PAGE </h1>
    {{ other_me|upper  }}
    <br>
    {{ other_2|cut:"rcb" }}
{% endblock %}

first_project_v1/templates/first_app/registration.html
<!DOCTYPE html>
{% extends "first_app/index.html" %}
{% block body_block %}
 
<div class = "jumbotron">
{% if registered %}
    <h1>Thank You for registtering!</h1>
{% else %}
<h1>Register Here</h1>
<h3>Fill out the form</h3>
<form enctype="multipart/form-data"   method="post">
{% csrf_token %}
{{user_form.as_p}}
{{profile_form.as_p }}
<input type="submit" value="Register">
</form>
{% endif %}
</div>
{% endblock %}

first_project_v1/templates/first_app/relative_url.html
<!DOCTYPE html>
{% extends "first_app/index.html" %}
{% block body_block %}
    <h1>Hey This is My Relative_URL PAGE </h1>
    {{ relative_me }}
    <br>
    <a href="{% url 'first_app:base' %}">BASE PAGE</a><br>
    <a href="{% url 'first_app:other' %}">OTHER PAGE</a><br>
    <a href="{% url 'index' %}">INDEX PAGE</a><br>
    <a href="{% url 'admin:index' %}">ADMIN PAGE</a><br>
{% endblock %}